package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.ProductInfo;
import pojo.ProductInfoExample;
import pojo.vo.ProductInfoVo;

public interface ProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Wed Mar 23 09:08:33 CST 2022
     */
    int countByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Wed Mar 23 09:08:33 CST 2022
     */
    int deleteByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Wed Mar 23 09:08:33 CST 2022
     */
    int deleteByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Wed Mar 23 09:08:33 CST 2022
     */
    int insert(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Wed Mar 23 09:08:33 CST 2022
     */
    int insertSelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Wed Mar 23 09:08:33 CST 2022
     */
    List<ProductInfo> selectByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Wed Mar 23 09:08:33 CST 2022
     */
    ProductInfo selectByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Wed Mar 23 09:08:33 CST 2022
     */
    int updateByExampleSelective(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Wed Mar 23 09:08:33 CST 2022
     */
    int updateByExample(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Wed Mar 23 09:08:33 CST 2022
     */
    int updateByPrimaryKeySelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Wed Mar 23 09:08:33 CST 2022
     */
    int updateByPrimaryKey(ProductInfo record);

    int deleteBatch(String []ids);

    List<ProductInfo> selectCondition(ProductInfoVo vo);



}